export const facilities = [
    'park',
    'hospital',
    'movie theater',
    'cinema',
    'supermarket',
    'grocery store',
    'train station',
    'gas station',
    'bus station',
    'airport',
    'museum',
    'theater',
    'police station',
    'school',
    'bookstore',
    'pet shop',
    'bar',
    'club',
    'restaurant',
    'bank',
    'post office'
]